name: build-and-test-workflow

on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - run: yarn install
      - run: cd plugins/plugin-chart-scatter && npm install
      - run: cd plugins/plugin-chart-table-extended && npm install
      - run: yarn build
      - run: yarn lint --quiet
      - run: yarn test
